### ISSUE TITLE
Whitespace at the bottom of the edit-master page...

### ISSUE THREAD

**Issue by TheFatherMind** [loewexy/pdnsmanager#56]
I know this is a bit of a petty request and I am sorry for that.  What is important is that I know it is.  (:

How do I add white space to the bottom fo the edit-master page.  It is very uncomfortable for me to go way down there with my mouse and eyes when typing in information on my laptop.  Also when I hit the add button on a record it pushes off the bottom of the page.  I want to be able to scroll it up a bit (or a lot) on the page.  Again.. really sorry to bother you all with this.  Formatting is not my specialty.

**Comment by loewexy** [comment]
Sorry I do not get what is your problem.

**Comment by mauricemeyer** [comment]
I see the issue here being two seperate issues:

# user comfort
You don't want to have the content on the bottom of the screen, so there should be whitespace added. This is heavily user specific, therefore this will not be implemented. If you have necessity for that, please try to achieve that in the browser directly.

# Adding records pushes off of the page
If the viewport is 100% full to the bottom, adding records will push "off the screen" to the bottom. This is unintended an will most likely be fixed by the 2.0 release as it will be a 100% rewrite of the frontend.

**Comment by TheFatherMind** [comment]
Because everyone loves to type at the very bottom of their screen.  And adding a few rows of white space at the bottom that allows them to scroll up or a setting to expand the size of the footer is.....  and adding the white space really has no effect on those people that do like to type at the very bottom of their screen.

I was actually just asking if there was a suggested or easy place to inject code to create that white space.  I do not mind hacking the software locally.  When I have time I will play with it and post my results here.  Thank you for responding!!  (:
